### ISSUE TITLE
syncing with davx5 (davdroid) leads to error

### ISSUE THREAD

**Issue by irgendwie** [jelmer/xandikos#108]
I'm encountering the following error on my xandikos instance when syncing via davx5:

> Jul 26 13:34:46 wheatley uwsgi[16427]: Traceback (most recent call last):
Jul 26 13:34:46 wheatley uwsgi[16427]:   File "/usr/lib/python3.7/site-packages/xandikos/store/__init__.py", line 270, in _iter_with_filter_indexes
Jul 26 13:34:46 wheatley uwsgi[16427]:     file_values = self.index.get_values(name, etag, keys)
Jul 26 13:34:46 wheatley uwsgi[16427]:   File "/usr/lib/python3.7/site-packages/xandikos/store/index.py", line 57, in get_values
Jul 26 13:34:46 wheatley uwsgi[16427]:     raise KeyError(etag)
Jul 26 13:34:46 wheatley uwsgi[16427]: KeyError: 'a51107ffad3dfa159bb75cdd1e7130b491ba0d2b'
Jul 26 13:34:46 wheatley uwsgi[16427]: During handling of the above exception, another exception occurred:
Jul 26 13:34:46 wheatley uwsgi[16427]: Traceback (most recent call last):
Jul 26 13:34:46 wheatley uwsgi[16427]:   File "/usr/lib/python3.7/site-packages/xandikos/webdav.py", line 1801, in __call__
Jul 26 13:34:46 wheatley uwsgi[16427]:     return do.handle(environ, start_response, self)
Jul 26 13:34:46 wheatley uwsgi[16427]:   File "/usr/lib/python3.7/site-packages/xandikos/webdav.py", line 1539, in handle
Jul 26 13:34:46 wheatley uwsgi[16427]:     app.properties, base_href, r, depth)
Jul 26 13:34:46 wheatley uwsgi[16427]:   File "/usr/lib/python3.7/site-packages/xandikos/webdav.py", line 273, in wrapper
Jul 26 13:34:46 wheatley uwsgi[16427]:     return _send_dav_responses(start_response, responses, DEFAULT_ENCODING)
Jul 26 13:34:46 wheatley uwsgi[16427]:   File "/usr/lib/python3.7/site-packages/xandikos/webdav.py", line 1289, in _send_dav_responses
Jul 26 13:34:46 wheatley uwsgi[16427]:     for response in responses:
Jul 26 13:34:46 wheatley uwsgi[16427]:   File "/usr/lib/python3.7/site-packages/xandikos/caldav.py", line 498, in report
Jul 26 13:34:46 wheatley uwsgi[16427]:     members=members):
Jul 26 13:34:46 wheatley uwsgi[16427]:   File "/usr/lib/python3.7/site-packages/xandikos/webdav.py", line 1049, in traverse_resource
Jul 26 13:34:46 wheatley uwsgi[16427]:     for (child_name, child_resource) in members(resource):
Jul 26 13:34:46 wheatley uwsgi[16427]:   File "/usr/lib/python3.7/site-packages/xandikos/web.py", line 469, in calendar_query
Jul 26 13:34:46 wheatley uwsgi[16427]:     filter=filter):
Jul 26 13:34:46 wheatley uwsgi[16427]:   File "/usr/lib/python3.7/site-packages/xandikos/store/__init__.py", line 274, in _iter_with_filter_indexes
Jul 26 13:34:46 wheatley uwsgi[16427]:     file_values = file.get_indexes(self.index.available_keys())
Jul 26 13:34:46 wheatley uwsgi[16427]:   File "/usr/lib/python3.7/site-packages/xandikos/store/__init__.py", line 121, in get_indexes
Jul 26 13:34:46 wheatley uwsgi[16427]:     ret[k] = list(self._get_index(k))
Jul 26 13:34:46 wheatley uwsgi[16427]:   File "/usr/lib/python3.7/site-packages/xandikos/store/__init__.py", line 111, in _get_index
Jul 26 13:34:46 wheatley uwsgi[16427]:     raise NotImplementedError(self._get_index)
Jul 26 13:34:46 wheatley uwsgi[16427]: NotImplementedError: <bound method File._get_index of <xandikos.store.File object at 0xffffb6c1df98>>
Jul 26 13:34:46 wheatley uwsgi[16427]: [pid: 16428|app: 0|req: 110/110] %some_ipv6% () {46 vars in 751 bytes} [Fri Jul 26 13:34:45 2019] REPORT /alex/calendars/work/ => generated 0 bytes in 233 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)

I'm not sure how to reproduce this issue really, it goes away for some time if I restart the xandikos instance but reappears after some time.
Syncing via vdirsyncer and sogo connector works without a problem.

Any ideas what is going on here?

Edit: davx5 complains about a "http 502 bad gateway" error.
Edit: The failing request seems to be:

> HTTP REQUEST:
Request{method=REPORT, url=https://%someurl%/alex/calendars/work/, tags={}}
`<?xml version='1.0' encoding='UTF-8' ?><CAL:calendar-query xmlns="DAV:" xmlns:CAL="urn:ietf:params:xml:ns:caldav"><prop><getetag /></prop><CAL:filter><CAL:comp-filter name="VCALENDAR"><CAL:comp-filter name="VEVENT" /></CAL:comp-filter></CAL:filter></CAL:calendar-query>`

**Comment by irgendwie** [comment]
The depth header seems to be a problem here, using depth=0 the request works when trying with curl, while using depth=1 leads to the error.

**Comment by irgendwie** [comment]
It seems like I found the source of the issue and it's not directly related to the software itself…
~1 month ago somehow *.xml files were added in my calendar directory - these files contain requests which were presumably added by some {cal,card,…}dav clients triggering some kind of bug I suggest since they are also logged in the git log:

> commit %somesha%
> Author: xandikos <xandikos@wheatley>
> Date:   Mon Jul 1 18:42:22 2019 +0000
> 
>     Added %someuuid%.xml
> 
> commit %somesha%
> Author: xandikos <xandikos@wheatley>
> Date:   Mon Jul 1 18:42:14 2019 +0000
> 
>     Added %someuuid%.xml

After removing them from the directory, the request doesn't fail anymore.
I'll open a new issue if this occurs again and I can provide more information.

**Comment by jelmer** [comment]
Hmm, it seems like Xandikos should ignore those files or at the very least provide a better error message.
