### ISSUE TITLE
SSL issue on https://www.xandikos.org

### ISSUE THREAD

**Issue by mahmoud** [jelmer/xandikos#109]
I get an unknown issuer when I visit https://www.xandikos.org/, just thought I'd let you know.

**Comment by worldworm** [comment]
https://github.com/Kickball/awesome-selfhosted/issues/1767

**Comment by jelmer** [comment]
The site should be back later today.

**Comment by jelmer** [comment]
Fixed.

**Comment by oxr463** [comment]
This is happening for me as well.

**Comment by jelmer** [comment]
Oops, this should be fixed again - sorry. I did set up monitoring and then I ended up not doing anything when I got notified.
