### ISSUE TITLE
Usage of haproxy in production

### ISSUE THREAD

**Issue by SpoortiPalakshaiah** [jelmer/xandikos#119]
Is there any way to expose port of the xandikos container using haproxy in production.

**Comment by jelmer** [comment]
Happy to try and help, but I don't have much experience with haproxy. If you found a way to get it to work with haproxy, any chance you could add a note under notes/haproxy.rst ?

**Comment by SpoortiPalakshaiah** [comment]
I used envoy instead of haproxy. I have used xandikos container. And I just exposed the port in envoy.
