### ISSUE TITLE
TypeError: uwsgi_spit() takes no keyword arguments

### ISSUE THREAD

**Issue by FrederikLauber** [jelmer/xandikos#124]
Hello, 
trying to setup a uwsgi driven xandikos instance.

My Ini looks like this:
[uwsgi]
http = 0.0.0.0:8001
master = true
cheaper = 0
processes = 5
plugins-dir = /usr/local/lib/uwsgi
plugin = router_basicauth,python3
route = ^/ basicauth:myrealm,joe:bar
module = xandikos.wsgi:app
env = XANDIKOSPATH=/home/joe/dav
env = CURRENT_USER_PRINCIPAL=/joe
env = AUTOCREATE=yes
env = DEFAULTS=yes

When accessing the service, I get this:

[pid: 6171|app: 0|req: 2/2] 100.64.40.1 (joe) {48 vars in 813 bytes} [Fri Jul 24 23:44:25 2020] GET / => generated 0 bytes in 2 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/home/joe/.local/lib/python3.6/site-packages/xandikos/webdav.py", line 1913, in handle_wsgi_request
    return response.for_wsgi(start_response)
  File "/home/joe/.local/lib/python3.6/site-packages/xandikos/webdav.py", line 119, in for_wsgi
    headers=self.headers)
TypeError: uwsgi_spit() takes no keyword arguments

Any tipps what is going in here? I already checked the other issues, I only found a mention of this in a previous docker image but there did not seem to be a fix besides updating some default values which I tried to do in the ini but it did not work :(

**Comment by jelmer** [comment]
What version are you running?

**Comment by FrederikLauber** [comment]
xandikos-0.2.2-py3.6.egg-info and python 3.6

uwsgi --version
2.0.19.1

**Comment by jelmer** [comment]
This should be fixed in master (a2a96c3e876bf79f8a91f312b1ffb8749d582688). I'll see if I can do another release.
