### ISSUE TITLE
CardBook sync only syncs about 50 files

### ISSUE THREAD

**Issue by FrederikLauber** [jelmer/xandikos#125]
Hello,

recently moved from nextCloud to Xandikos as my contact management software of choice and after some growing pain (the multi processor race condition), I finally got everything up and working.
Well, almost, I noticed that Xandikos with Cardbook only syncs about 50 contacts per sync. While this does not seem to be an issue 
in normal operations, importing my initial contacts took quite some time and nerv.
Is this expected behavior and if not, is there anything i can do about this? I never noticed this behavior with nextcloud or the like before so my guess it is not in Cardbok but Xandikos.

Cheers,

**Comment by jelmer** [comment]
There are no limits on the number of contacts to sync on the Xandikos side - it's up to the client to specify how many it would like to receive.

CardBook happily synchronizes more than 50 contacts for me on initial sync (I just set up my cardbook addressbook from scratch) - in fact, it did about 1900 in 40 card chunks.

It looks like this is a limitation on the CardBook side after the initial sync - see the "Synchronization" page in the "CardBook Preferences", where you can specify the maximum number of contacts to push per sync (after the initial sync, I think/). I don't think there is anything that Xandikos can do here.

**Comment by FrederikLauber** [comment]
Thanks, that fiyed it, sorry for the noise
