### ISSUE TITLE
handle HTTP: Expect

### ISSUE THREAD

**Issue by castaway** [jelmer/xandikos#126]
https://github.com/jelmer/xandikos/blob/74baad17f99394a8ecbc3c7ff8b78f79ecfe759f/xandikos/webdav.py#L1932-L1933

Hi, I'm trying to use [Rainlendar](http://www.rainlendar.net/cms/index.php) to talk to a local install of xandikos (0.2.3), its sending an Expect header, and I'm getting both a "100-continue" response, as well as a "417 Expectation failed" (I think the first one is sent by aiohttp by default? from here presuambly - https://github.com/aio-libs/aiohttp/blob/2a924cae6c19dbbfde220bbd461fc446764ad156/aiohttp/web_urldispatcher.py#L261

If I remove the two lines in xandikos webdav.py linked above, then Rainlendar queries xandikos just fine.

**Comment by jelmer** [comment]
I suspect we'll need to need follow the instructions here: https://docs.aiohttp.org/en/stable/web_advanced.html#expect-header

That should be fairly straightforward - I'll see if I can make that change this week.
