### ISSUE TITLE
Is there a document of all the bin/xandikos arguments?

### ISSUE THREAD

**Issue by castaway** [jelmer/xandikos#128]
I was looking for "how to listen on 0.0.0.0 instead of localhost", I eventually tracked them down:

https://github.com/jelmer/xandikos/blob/f321bf60aea1457b227c35790b743dff6be53a57/xandikos/web.py#L1109

is there a doc I just missed? (If not happy to write one..)

**Comment by jelmer** [comment]
There should probably be a manual page; in the absence of that, "xandikos --help" should at least give you a summary of the different arguments and brief explanation of their uses.

**Comment by castaway** [comment]
.. I'm not sure why I didnt try that.. I did try no arguments at all, which doesn't hint at "--help" tho..
