### ISSUE TITLE
Possible regression 0.2.3 -> 0.2.4, server freeze in propfind

### ISSUE THREAD

**Issue by tobixen** [jelmer/xandikos#131]
My xandikos installed through ArchLinux repositories upgraded xandikos from 0.2.3 to 0.2.5 at the 20th of February.  When doing a pip install, I get 0.2.4.  With both 0.2.4 and 0.2.5, functional tests (nosetests) on the python caldav client library fails. Downgrading to 0.2.3, everything works as expected.

The xandikos server is launched like this from the unit tests:

```python
        self.serverdir = tempfile.TemporaryDirectory()
        self.serverdir.__enter__()
        ## TODO - we should do something with the access logs from Xandikos
        self.backend = XandikosBackend(path=self.serverdir.name)
        self.backend.create_principal('/sometestuser/', create_defaults=True)
        self.xandikos_server = make_server(xandikos_host, xandikos_port, XandikosApp(self.backend, '/sometestuser/'))
        self.xandikos_thread = threading.Thread(target=self.xandikos_server.serve_forever)
        self.xandikos_thread.start()
```

And the request that freezes goes roughly like this (I didn't check the actual tcp communication, but this is what is sent to the requests library):

```
PROPFIND http://localhost:8993/

User-Agent: Mozilla/5.0
Content-Type: text/xml
Accept: text/xml, text/calendar
Depth: 0

<?xml version='1.0' encoding='utf-8'?>
<D:propfind xmlns:D="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav"><D:prop><D:current-user-principal/></D:prop></D:propfind>
```

I can also reproduce the freeze through curl:

```sh
curl -X PROPFIND 'http://user1:password1@localhost:8993/' --data '<?xml version='"'"'1.0'"'"' encoding='"'"'utf-8'"'"'?>\n<D:propfind xmlns:D="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav"><D:prop><D:current-user-principal/></D:prop></D:propfind>' -H 'Content-Type: text/xml'
```

**Comment by tobixen** [comment]
This was due to xandikos going async, and hence my threaded way of starting it didn't work out anymore.  I've managed to work around the issue now.

**Comment by jelmer** [comment]
Sorry about breaking this; let me know if I can help with something that is better than a workaround.

**Comment by tobixen** [comment]
It would be nice to have some high-level python methods for starting and stopping a server.  web.main is a bit of a mix of code for processing the command line arguments and the code needed to start up a server, it would probably be an idea to split it in two.

I ended  up now with a quite ugly code block in my test code now for spawning a xandikos test server in a thread for each test and rigging it down in the test shutdown (commit coming soon).  I should probably consider to make the caldav library async as well, but I don't have much experience with async programming, and I also think it's important to keep backward compatibility.

**Comment by jelmer** [comment]
I've added a xandikos.web.run_simple_server() function that hopefully does what you need.

**Comment by tobixen** [comment]
Cool.  I should look into it eventually ... but as long as my current code works, I'll just add a comment to the code and procrastinate that :-)

**Comment by tobixen** [comment]
I'm writing up ftests for my [plann](https://github.com/tobixen/plann) project now, so the `xandikos.web.run_simple_server()`  seems to be useful for me eventually :-)

So I'm able to spin up a server - but I think there is no easy way for me to shut it down gracefully.
