### ISSUE TITLE
OIDC/OAuth2 support

### ISSUE THREAD

**Issue by ibotty** [jelmer/xandikos#138]
It would be great to allow authenticating using OpenIDConnect.  That makes single sign-on as well as MFA possible.

A strategy might be to recommend a proxy in front of xandikos that will pass certain headers.

**Comment by jelmer** [comment]
Yeah, something like apache with https://github.com/zmartzone/mod_auth_openidc should be sufficient for that. I'm a bit hesitant to provide more documentation than just a pointer to that. It's hard to be exhaustive and up-to-date, and there are plenty of guides for setting up OIDC using e.g. apache as a reverse proxy out there.

**Comment by ibotty** [comment]
I prefer a more micro-service oriented service like https://github.com/oauth2-proxy/oauth2-proxy, but of course apache with mod_auth_openidc would work as well.  I see that xandikos does not support multi-user anyway so it's not necessary to pass the user and scopes to it.

**Comment by jelmer** [comment]
That's part of why I'm hesitant to go this route, since I don't really want to document all the possible kinds of authentication and the ways they can be configured.  Maybe we could just provide a simple example for a common setup, or provide some pointers.
