### ISSUE TITLE
Git store needs working directory to be absolute to successfully execute hooks

### ISSUE THREAD

**Issue by oatmealraisin** [jelmer/xandikos#140]
I just finished a deployment, and I had set up a few git hooks. Upon quite a bit of debugging, I found that the `subprocess.call` call made by the dulwich library was returning a `FileNotFound` error, which it was being silenced. I changed my execution `-d` flag to be an absolute path, and everything worked.

If possible, it would probably be more user friendly to expand relative paths in flags, as there isn't much in the way of error logging in this section of the codebase :)

**Comment by jelmer** [comment]
On Sun, Nov 28, 2021 at 05:36:06PM -0800, Ryan Murphy wrote:
> I just finished a deployment, and I had set up a few git hooks. Upon quite a bit of debugging, I found that the `subprocess.call` call made by the dulwich library was returning a `FileNotFound` error, which it was being silenced. I changed my execution `-d` flag to be an absolute path, and everything worked.
> 
> If possible, it would probably be more user friendly to expand relative paths in flags, as there isn't much in the way of error logging in this section of the codebase :)

Was there a specific hook (post-receive?) that you experienced this
with?

-- 
Jelmer Vernooĳ ***@***.***>
PGP Key: https://www.jelmer.uk/D729A457.asc

**Comment by jelmer** [comment]
There have been some improvements to the hooks handling in Dulwich (which Xandikos is built on top of) that I think should have resolved this issue. Please reopen (and mention which hooks you're having trouble with) if you can still reproduce this.

**Comment by oatmealraisin** [comment]
Howdy! Sorry for not responding to this last time. I've come back to this over the past few days, here's a bit more information

The `post-commit` hook is very simple, 

```bash
#!/usr/bin/bash

git push origin master
```

And is installed to the `.git/hooks/` directory, given 777 perms. The full run script is here:

```bash
WORKDIR="data/user"
GITDIR=${WORKDIR}/calendars/calendar
GITURL="****"

mkdir -vp ${WORKDIR}/{calendars,contacts}

git config --global user.email "****"
git config --global user.name "****"

git clone ${GITURL} ${GITDIR}
git -C ${GITDIR} remote -v 
cp post-commit ${GITDIR}/.git/hooks/
chmod 777 ${GITDIR}/.git/hooks/post-commit
git -C ${GITDIR} log -1

uwsgi uwsgi.ini
#python3 -m xandikos.web --port=${PORT} --listen-address=0.0.0.0 -d /app/data
```

I'm deploying to Heroku, here's my wsgi.ini:

```ini
[uwsgi]
http-socket = :$(PORT)
die-on-term = true
umask = 022
master = true
cheaper = 0
processes = 1
plugin = router_basicauth,python3
route = ^/ basicauth:myrealm,****:****
module = xandikos.wsgi:app
env = XANDIKOSPATH=/app/data/
env = CURRENT_USER_PRINCIPAL=/user/
env = AUTOCREATE=defaults
```

The issue I've found comes from the `XANDIKOSPATH` variable, or `-d` flag. If the path is relative, e.g. `data/`, Xandikos operates fine, but the `post-commit` hook isn't run.

If we set it instead to an absolute path, e.g. `/app/data`, the hook works fine.

This is because of how Dulwich runs the script, `ret = subprocess.call([self.filepath] + list(args), cwd=self.cwd)` (from `dullwich/vhooks.py:103`

**Comment by jelmer** [comment]
This should be fixed now - please let me know if you're still able to reproduce it.
