### ISSUE TITLE
How is data stored in git?

### ISSUE THREAD

**Issue by chmac** [jelmer/xandikos#141]
I've looked through the issues and read the readme, but I can't see how the data is actually stored on disk in the git repo. Is that documented anywhere?

Forgive me if it's part of the RFCs referenced in the readme. I'm not familiar with the *Dav protocols in that much detail.

My question is also whether or not I could edit the data on disk and use xandikos as a *Dav <-> filesystem frontend. If there's internal caching for example, then I guess this approach wouldn't work.

Finally, thanks for this software, I'm looking to move all of my personal data into various locations that are stored in plain text and can be easily readable for the long term. This looks to be an excellent fit.

**Comment by jelmer** [comment]
It's stored in git as plain files uploaded using webdav; so for calendar entries that'd be icalendar files and for addressbook files it's vcard files. You can also upload arbitrary other files using WebDAV.

There is internal caching in xandikos, but this is refreshed when third party changes are made to the repository.You could use xandikos as a *Dav filesystem frontend. What is primarily provided today is storage backed by a Git repository, but you could run it with the plain filesystem backend as well.

**Comment by chmac** [comment]
@jelmer Awesome, thanks for the clarification. I also thought of using git to manage the folder. It sounds like pushing changes via git would also work with the existing caching methods.

Happy to close this now as the question is answered.
