### ISSUE TITLE
Broken links on website

### ISSUE THREAD

**Issue by chmac** [jelmer/xandikos#146]
>See examples/uwsgi.ini for an example uWSGI configuration.

Links to: https://www.xandikos.org/code/raw/master/examples/uwsgi.ini

Which is a 404.

I guess it's generated from a markdown file and maybe wants to link to the GitHub repo?

**Comment by jelmer** [comment]
I think the issue is that the repository has somehow disappeared from klaus; I'll take a look.

**Comment by jelmer** [comment]
Fixed.
