### ISSUE TITLE
Add easy link to GitHub on website?

### ISSUE THREAD

**Issue by chmac** [jelmer/xandikos#147]
Would you be open to adding a link to this GitHub repo on the xandikos.org site? Either in the menu at the top or in the footer would be great.

**Comment by jelmer** [comment]
There are links already on the https://www.xandikos.org/contributing.html and https://www.xandikos.org/download.html pages; what did you have in mind?

**Comment by jelmer** [comment]
I've pushed the website repository to https://github.com/xandikos/homepage if you'd like to contribute

**Comment by chmac** [comment]
> There are links already on the https://www.xandikos.org/contributing.html and https://www.xandikos.org/download.html pages; what did you have in mind?

You're absolutely right. Somehow I'm attuned to the idea that I'm searching the page for a link called GitHub and so it takes me a few extra mental cycles to get to the Contributing page.

I was thinking something in the footer. I'll put in a PR now, just figured out what I think will work!
