### ISSUE TITLE
Potential issue with supported-report-set

### ISSUE THREAD

**Issue by chmac** [jelmer/xandikos#149]
I'm using [tsdav](https://tsdav.vercel.app/) to connect to xandikos. During it's [`fetchAddressBooks()`](https://tsdav.vercel.app/docs/carddav/fetchAddressBooks) call, I see the following request being sent to xandikos:

```xml
 <?xml version="1.0" encoding="utf-8"?>
 <d:propfind xmlns:c="urn:ietf:params:xml:ns:caldav" xmlns:ca="http://apple.com/ns/ical/" xmlns:cs="http://calendarserver.org/ns/" xmlns:card="urn:ietf:params:xml:ns:carddav" xmlns:d="DAV:">
   <d:prop>
     <d:supported-report-set/>
   </d:prop>
 </d:propfind>
```

And I see the following response back:

```xml
<ns0:multistatus xmlns:ns0="DAV:" xmlns:ns1="urn:ietf:params:xml:ns:carddav">
  <ns0:response>
    <ns0:href>/user/contacts/addressbook/</ns0:href>
    <ns0:propstat>
      <ns0:status>HTTP/1.1 200 OK</ns0:status>
      <ns0:prop>
        <ns0:supported-report-set>
          <ns0:supported-report>
            <ns1:addressbook-multiget />
          </ns0:supported-report>
          <ns0:supported-report>
            <ns1:addressbook-query />
          </ns0:supported-report>
          <ns0:supported-report>
            <ns0:expand-property />
          </ns0:supported-report>
          <ns0:supported-report>
            <ns0:sync-collection />
          </ns0:supported-report>
        </ns0:supported-report-set>
      </ns0:prop>
    </ns0:propstat>
  </ns0:response>
  < ... snip ... >
</ns0:multistatus>
```

If I compare this output to what I get from FastMail, there's a level missing. In the FastMail output I have `supported-report-set`, `supported-report` and then a `report` before the report itself. Could it be that this is a xandikos bug?

**Comment by jelmer** [comment]
The spec is here: https://datatracker.ietf.org/doc/html/rfc3253#section-3.1.5, so it does indeed look like we're missing a report element in there.

**Comment by chmac** [comment]
@jelmer Awesome, thanks for the quick response. When do you think this fix will land on the docker registry?

**Comment by jelmer** [comment]
I can publish a new version this weekend

**Comment by chmac** [comment]
@jelmer Awesome, thanks a lot. If you would be so kind as to pop an update here once it's out that would be doubly great, then I can update right away and take the hack out of my client code! :-)

**Comment by jelmer** [comment]
This has now been published
