### ISSUE TITLE
Any option to protect against collection deletions?

### ISSUE THREAD

**Issue by chmac** [jelmer/xandikos#150]
The thing I like most about xandikos is that the data is stored in git. This gives me confidence I can restore data in case of errors, inspect the history, and so on.

However, I've just had an issue where (during my testing thankfully), an address book was deleted. I didn't plan to delete the whole address book, I only tried to delete all of its contacts. Then I realised that the whole directory on the server, including its `.git` directory, have disappeared. So now I have no history to be able to restore.

Is there any way to protect against this? I guess I could setup some git hooks so that git pushes automatically after every commit. But that would also get deleted during a wipe. Curious to hear if there are any other strategies.

Also, is it an intended behaviour that the address book is deleted whenever all of its contents are deleted? I'm writing some sync code, and one option is to remove all contacts so as to ensure the address book is empty before pushing. But that might not work in this case. Or maybe this behaviour is a part of the spec?

**Comment by chmac** [comment]
Okay, so I figured out that my client is misbehaving and deleting the collection instead of the records under some cases.

Still curious to know if I can ensure that my git repos can't be deleted even if a collection is deleted.

**Comment by jelmer** [comment]
I think #62 might address your use case. At the moment, since each collection is a git repository it's going to be hard to implement this in a reasonable way *and* allow you to manage collections from your DAV client. E.g. if we allow you to create collections we should also give you the ability to delete them.

**Comment by chmac** [comment]
@jelmer Yep, makes sense. I've also since found and fixed the issue with the client, so now it's less of an issue for me personally. Happy to close this in favour of #62.

**Comment by jelmer** [comment]
Ack, let's do that.
