### ISSUE TITLE
No executable script on Windows

### ISSUE THREAD

**Issue by MisterY** [jelmer/xandikos#163]
Related to the discussion [here](https://github.com/jelmer/xandikos/issues/161#issuecomment-1064329464), I've figured out what the problem is. On Windows, scripts `xandikos` and `xandikos.py` are created in the Python Scripts folder.
However, not having an extension, the `xandikos` script is not considered to be an executable file.
If I remember well, Python normally creates .bat files as executables in the script directory, if an entry point is defined for a console script in setup.py.

**Comment by MisterY** [comment]
Also, when running the xandikos.py script:

![image](https://user-images.githubusercontent.com/462445/158040326-53e04385-4d65-403e-a3c0-80fbde4793e0.png)

**Comment by jelmer** [comment]
That's really something dependent on the way you install Xandikos rather than Xandikos itself.

Happy to take reasonable patches to improve things.

**Comment by MisterY** [comment]
Hmm... Well, look at this: if I install Xandikos via pip and run

```
pip install xandikos
xandikos
```
I get `'xandikos' is not recognized as an internal or external command,
operable program or batch file.`

On the other hand, if I install [cashiersync](https://gitlab.com/alensiljak/cashiersync) and run:

```
pip install cashiersync
cashiersync
```
it runs fine on Windows, Linux, Termux...

The missing piece of magic could be:

```
    entry_points={
        'console_scripts': [
            'cashiersync = cashiersync.main:run_server',
        ],
    },
```

if I remember well. I see that you have the `scripts` entry in setup.py but no `entry_points`. Could that be the reason? 

I will try to play around with this.
