### ISSUE TITLE
Search on category field yields nothing

### ISSUE THREAD

**Issue by tobixen** [jelmer/xandikos#191]
I'm currently implementing support for search by category and other stuff in the python caldav client library.

I have this test data in my calendar (an example from RFC5545):

```icalendar
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Example Corp.//CalDAV Client//EN
BEGIN:VEVENT
UID:19970901T130000Z-123403@example.com
DTSTAMP:19970901T130000Z
DTSTART;VALUE=DATE:19971102
SUMMARY:Our Blissful Anniversary
TRANSP:TRANSPARENT
CLASS:CONFIDENTIAL
CATEGORIES:ANNIVERSARY,PERSONAL,SPECIAL OCCASION
RRULE:FREQ=YEARLY
END:VEVENT
END:VCALENDAR
```

And I'm doing a REPORT search like this:

```xml
<C:calendar-query xmlns:D="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav">
  <D:prop>
    <C:calendar-data/>
  </D:prop>
  <C:filter>
    <C:comp-filter name="VCALENDAR">
      <C:comp-filter name="VEVENT">
        <C:prop-filter name="CATEGORIES">
          <C:text-match collation="i;octet">PERSONAL</C:text-match>
        </C:prop-filter>
      </C:comp-filter>
    </C:comp-filter>
  </C:filter>
</C:calendar-query>
```

Which, if I've understood the RFCs correctly, should yield the example calendar object - but, no - an empty list is returned:

```
<multistatus xmlns="DAV:" />
```

I tested matching on the `CLASS` property, if I ask for a text match on CONFIDENTIAL it is returned.  If I ask for a text match on CONF it is not returned.  While that behaviour does make sense to me, at least in this context, I think the RFC states that it should match.

**Comment by tobixen** [comment]
The caldav library now has a tag bug-xandikos-191 for reproducing this issue

```bash
git clone git@github.com:python-caldav/caldav.git
cd caldav
git checkout bug-xandikos-191
nosetests3 tests.test_caldav:TestLocalXandikos.testSearchEvent
```

**Comment by tobixen** [comment]
I'm kind of stuck now as I need this functionality to work for continuing testing/building my client side search method ... so I'm allowing myself to look a bit into this one :-)

**Comment by tobixen** [comment]
The `icalendar.prop` module defines quite some v*-classes.  Those seems particularly relevant for a text match:

* `vCalAddress`
* `vURI`
* `vCategory`
* `vText`

... so it seems like `vCategory` is a special case.  Looking into the RFC, it's actually the only property with a plural name.  I thought there were more of them, but I was probably mistaken.

Probably the `vURI` and `vCalAddress` also needs special handling, but I'll start with writing up a pull request for only categories so far ... and without test code.

**Comment by jelmer** [comment]
Actually, reading the RFC it's not clear to me whether matching is meant to happen on individual categories or on the serialized string ("TRAVEL,BLAH"), and in either case - where the intended serialization is documented.

Do you know how that's supposed to work?

**Comment by tobixen** [comment]
The RFC is very unclear - however, three thoughts here:

* it does say "substring search" in the RFC
* "CATEGORIES:foo,bar,zoo" is equivalent with "CATEGORIES:zoo,bar,foo", so it doesn't make sense to do search on the full string
* Personally I think it makes most sense to do a full word match towards each category and return if one of them matches

I added a test towards weather other servers would match 'zoo,bar,foo', but I was too lazy to collect the results from it (just did an `assert len(matches) in (0,1)` as for now).  I'm searching for my notes on which servers did a full-text-match and which servers did a substring match.

**Comment by tobixen** [comment]
So I have those compatibility flags:

* category_search_yields_nothing: When querying for a text match report over fields like the category field, server returns nothing
* text_search_is_case_insensitive: Probably not supporting the collation used by the caldav library
* text_search_is_exact_match_only: Searching for 'CONF' i.e. in the class field will not yield CONFIDENTIAL.  Which generally makes sense, but the RFC specifies substring match
* text_search_is_exact_match_sometimes: Some servers are doing an exact match on summary field but substring match on category
* combined_search_not_working: When querying for a text match and a date range in the same report, weird things happen
* text_search_not_working: Text search is generally broken
* radicale_breaks_on_category_search: See https://github.com/Kozea/Radicale/issues/1125

Servers tested:

* Xandikos: text_search_is_exact_match_only, category_search_yields_nothing
* Radicale:  radicale_breaks_on_category_search, text_search_is_case_insensitive (there is a note in the code that collations aren't supported), text_search_is_exact_match_only
* Zimbra: category_search_yields_nothing, text_search_is_exact_match_only
* Baikal: combined_search_not_working, text_search_is_exact_match_sometimes
* Nextcloud and fastmail: combined_search_not_working, text_search_is_exact_match_sometimes
* Robur: text_search_not_working

**Comment by jelmer** [comment]
Ack, thanks for the detailed explanation! Let's go with this option then.

I'll take a look at how this works with indexes today (we may have to deserialize first), and then I'll merge.
