### ISSUE TITLE
Another cache bug

### ISSUE THREAD

**Issue by tobixen** [jelmer/xandikos#221]
It can probably be argued weather this makes sense at all :-)  ... but in any case, I expect consistent results when doing searches, always.

Here is my task (if I understand the RFC correctly, this is a valid way to mark up that a recurring task has been done once):

```icalendar
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Example Corp.//CalDAV Client//EN
BEGIN:VTODO
CATEGORIES:CHORE
DTSTAMP:20221013T151313Z
DTSTART:20221017T065500Z
DURATION:PT10M
PRIORITY:3
RRULE:FREQ=WEEKLY;COUNT=3;BYMINUTE=55;BYHOUR=6;BYDAY=MO
STATUS:NEEDS-ACTION
SUMMARY:Take out the thrash before the collectors come.
UID:takeoutthethrash
END:VTODO
BEGIN:VTODO
CATEGORIES:CHORE
COMPLETED;VALUE=DATE-TIME:20221019T172311Z
DTSTAMP:20221013T151313Z
DTSTART:20221017T065500Z
DURATION:PT10M
PRIORITY:3
RECURRENCE-ID:20221017T065500Z
SEQUENCE:1
STATUS:COMPLETED
SUMMARY:Take out the thrash before the collectors come.
UID:takeoutthethrash
END:VTODO
BEGIN:VTODO
CATEGORIES:CHORE
DTSTAMP:20221013T151313Z
DTSTART;VALUE=DATE-TIME:20221024T065500Z
DUE;VALUE=DATE-TIME:20221024T070500Z
PRIORITY:3
RECURRENCE-ID;RANGE=THISANDFUTURE;VALUE=DATE-TIME:20221024T065500Z
SEQUENCE:2
STATUS:NEEDS-ACTION
SUMMARY:Take out the thrash before the collectors come.
UID:takeoutthethrash
END:VTODO
END:VCALENDAR
```

And here is the report query:

```XML
<C:calendar-query xmlns:D="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav">
  <D:prop>
    <C:calendar-data/>
  </D:prop>
  <C:filter>
    <C:comp-filter name="VCALENDAR">
      <C:comp-filter name="VTODO">
        <C:prop-filter name="COMPLETED">
          <C:is-not-defined/>
        </C:prop-filter>
        <C:prop-filter name="STATUS">
          <C:text-match collation="i;octet">NEEDS-ACTION</C:text-match>
        </C:prop-filter>
      </C:comp-filter>
    </C:comp-filter>
  </C:filter>
</C:calendar-query>
```

The report query returns the task six times, but no luck on the seventh time.  Same behavior in master and in "my" 5f03c3c0fd8166ffc54a1ddf3ddc399a6c2067f8.

(It's an open question if this should or should not catch the icalendar above ... but as said, in any case I expect consistency.  This report query was actually sort of a mistake, when removing the check for COMPLETED not defined I got sane and consistent data back from xandikos)

(Can we make the threshold configurable?  I.e. try to read from `os.environ` when setting `store.index.INDEXING_THRESHOLD`?)

**Comment by jelmer** [comment]
recurring events aren't support yet - see #8

> (Can we make the threshold configurable? I.e. try to read from os.environ when setting store.index.INDEXING_THRESHOLD?)
What's the threshold you're referring to?

**Comment by tobixen** [comment]
I didn't say I'd like to disable the cache - actually I was more thinking to set it to 0 when running tests locally, to catch those bugs faster.

I also think it's irrelevant weather the calendar supports recurrences or not, the important thing here is that the behaviour is consistent regardless of weather content exists in the cache or not.

**Comment by jelmer** [comment]
Sorry, fair enough - I'd be open to supporting some way of changing the threshold for testing purposes

recurring events that are half-supported (even with cache disabled) can indeed lead to confusing behaviour; the only real way of preventing that (until recurring event support lands) is to altogether reject the upload of any ics files that contain recurring events.

**Comment by jelmer** [comment]
To be pedantic, this isn't a cache - the indexes are only used to determine what files are relevant. Contents are still returned from the file on disk.

I'd forgotten, but there is a paranoid mode that will double check that contents from the indexes match what would be returned without the indexes. That's also something we could add a flag for. (Of course, this has performance consequences)

**Comment by jelmer** [comment]
Closing this in favour of #8
