### ISSUE TITLE
support cloning git repositories

### ISSUE THREAD

**Issue by jelmer** [jelmer/xandikos#232]
With the new aiohttp support in Dulwich, we could make the Xandikos repositories cloneable over HTTP. There are some caveats to watch out for here. For example, if we allow write-access, we should possibly reject anything that adds invalid files.

**Comment by hxtmdev** [comment]
@jelmer do you want to close this as "cloning" is possible now, or leave it open for smart protocol and write-access?

**Comment by jelmer** [comment]
Let's close this - we can open a new one for write access.
