### ISSUE TITLE
encoding inconsistencies for collection names

### ISSUE THREAD

**Issue by jelmer** [jelmer/xandikos#26]
when creating collections via MKCOL, xandikos seems to use latin-1 encoding. However, when accessing collections, it uses utf-8.

% LC_ALL=C.UTF-8 ls    
calendar  test  test @ foo Ã¤t bar-vdirsyncer-ci-5b7ed28d-be75-46e2-9daa-65e03d1f2f57  test @ foo Ã¤t bar-vdirsyncer-ci-ba578f29-0f5f-4772-a777-18ca3df8a2ba

(Ã¤ should actually be an a-umlaut)

Found by vdirsyncer's test_specialchars.

**Comment by jelmer** [comment]
the problem appears to be that wsgiref decodes PATH_INFO and assumes latin-1; by the time PATH_INFO makes it to xandikos, it is already decoded.

**Comment by untitaker** [comment]
This is one of those tests that are practically irrelevant and which may be reintroduced by whichever WSGI server or reverse proxy the admin ends up using.

**Comment by jelmer** [comment]
Pushed a fix for this in the vdirsyncer-latin-1 branch. I'm not sure what the correct fix is. Can/should we assume that the paths in PUT requests are UTF-8?

**Comment by untitaker** [comment]
Ah, I think I remember. This occured when porting Werkzeug: http://werkzeug.pocoo.org/docs/0.11/python3/#wsgi-environment

**Comment by untitaker** [comment]
And then this: https://github.com/pallets/werkzeug/blob/master/werkzeug/_compat.py#L175

**Comment by untitaker** [comment]
And this: https://github.com/pallets/werkzeug/blob/master/werkzeug/wsgi.py#L43

**Comment by untitaker** [comment]
I don't see a `vdirsyncer-latin-1` branch

**Comment by untitaker** [comment]
Ah, here: https://jelmer.uk/code/xandikos/commit/0b39fd05d31ff9941bb497131eeb55308e1ef6c3/

I wouldn't necessarily recommend overwriting the old value, but rather making a wrapper function `path_from_environ` and use it everywhere. That function can cache the fixed value in a separate key.

**Comment by jelmer** [comment]
I was hoping there was a way to figure out the encoding for the Request-URI, but I guess HTTP doesn't define one. Assuming it's UTF-8 is going to break people who send iso-8859-1 encoded paths (though how many are there?), but it seems like that's the right thing to do.

Adding a path_from_environ function rather than overwriting is a good idea, I'll see if I can do that.

**Comment by untitaker** [comment]
Should be fixed by https://github.com/jelmer/xandikos/commit/53e6e7d9d1df86a54fe5c78ce6f54c665da70f12 ?

**Comment by jelmer** [comment]
Yep!
