### ISSUE TITLE
listening on default address as well as systemd sockets

### ISSUE THREAD

**Issue by schnusch** [jelmer/xandikos#260]
<https://github.com/jelmer/xandikos/blob/c4f1953601a179996f3152fb63e6851315518865/xandikos/web.py#L1544-L1549>

I think `if socket_path:` should be `elif socket_path:`, so the `TCPSite` is not added with `listen_address=None` and `listen_port=None`, which uses aiohttp's default host and port.

**Comment by jelmer** [comment]
Happy to accept a patch that does that
