### ISSUE TITLE
make style requires isort which may not always be installed

### ISSUE THREAD

**Issue by icedwater** [jelmer/xandikos#266]
I tried to run `make style` immediately after cloning a clean fork of this repo. It failed because isort wasn't installed. When I tried to install isort on my system, it gave me an Ubuntu package (probably just a symlink) and also installed Ubuntu's `python3-isort` package. This was version 4.3.4. `pip install isort` gives me 5.1.2 at this time.

In this case, I suggest updating the Makefile so that the python module `isort` is used instead, this can be installed within a dev virtual environment where needed.

I'll submit a pull request for this.

**Comment by jelmer** [comment]
No objections against invoking isort via the module. However, do you have any indications that isort 4 is actually not sufficient here?

**Comment by icedwater** [comment]
No, I don't think I've anything against a particular version. In fact, the environment can specify whatever version is preferred - my main issue was that it should use the Python module, preferably inside a virtual environment, rather than assume the system has already installed it.
