### ISSUE TITLE
list subcollections

### ISSUE THREAD

**Issue by jelmer** [jelmer/xandikos#27]
Any store-based collections currently only return object members, and not subcollections.

**Comment by jelmer** [comment]
Fixed in master now, though the API could use further improvements.

**Comment by legrostdg** [comment]
It does not seem to work with `vdirsyncer discover`:

The first run of `vdirsyncer discover` works, and creates the calendars, but the second run fails, as before:

    $ vdirsyncer -vdebug discover my_calendars
    debug: Using 1 maximal workers.
    Discovering collections for pair my_calendars
    calendars_local:
      - "home"
      - "work"
    debug: PROPFIND http://localhost:8080/
    debug: {'Depth': '1', 'User-Agent': 'vdirsyncer', 'Content-Type': 'application/xml; charset=UTF-8'}
    debug: 
    debug:     <d:propfind xmlns:d="DAV:">
    debug:         <d:prop>
    debug:             <d:resourcetype />
    debug:         </d:prop>
    debug:     </d:propfind>
    debug:     
    debug: Sending request...
    debug: 207
    debug: {'Content-Length': '253', 'Content-Type': 'text/xml; charset="utf-8"'}
    debug: <ns0:multistatus xmlns:ns0="DAV:"><ns0:response><ns0:href>/</ns0:href><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:propstat><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:prop><ns0:resourcetype /></ns0:prop></ns0:propstat></ns0:response></ns0:multistatus>
    debug: Skipping, not of resource type {urn:ietf:params:xml:ns:caldav}calendar: <Element '{DAV:}response' at 0x7fc2353cbd18>
    debug: Given URL is not a homeset URL
    debug: PROPFIND http://localhost:8080/
    debug: {'Depth': '0', 'User-Agent': 'vdirsyncer', 'Content-Type': 'application/xml; charset=UTF-8'}
    debug: 
    debug:         <d:propfind xmlns:d="DAV:">
    debug:             <d:prop>
    debug:                 <d:current-user-principal />
    debug:             </d:prop>
    debug:         </d:propfind>
    debug:         
    debug: Sending request...
    debug: 207
    debug: {'Content-Length': '318', 'Content-Type': 'text/xml; charset="utf-8"'}
    debug: <ns0:multistatus xmlns:ns0="DAV:"><ns0:response><ns0:href>/</ns0:href><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:propstat><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:prop><ns0:current-user-principal><ns0:href>/user/</ns0:href></ns0:current-user-principal></ns0:prop></ns0:propstat></ns0:response></ns0:multistatus>
    debug: PROPFIND http://localhost:8080/user/
    debug: {'Depth': '0', 'User-Agent': 'vdirsyncer', 'Content-Type': 'application/xml; charset=UTF-8'}
    debug: 
    debug:     <d:propfind xmlns:d="DAV:" xmlns:c="urn:ietf:params:xml:ns:caldav">
    debug:         <d:prop>
    debug:             <c:calendar-home-set />
    debug:         </d:prop>
    debug:     </d:propfind>
    debug:     
    debug: Sending request...
    debug: 207
    debug: {'Content-Length': '366', 'Content-Type': 'text/xml; charset="utf-8"'}
    debug: <ns0:multistatus xmlns:ns0="DAV:" xmlns:ns1="urn:ietf:params:xml:ns:caldav"><ns0:response><ns0:href>/user/</ns0:href><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:propstat><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:prop><ns1:calendar-home-set><ns0:href>/gueux/calendars/</ns0:href></ns1:calendar-home-set></ns0:prop></ns0:propstat></ns0:response></ns0:multistatus>
    debug: PROPFIND http://localhost:8080/user/calendars/
    debug: {'Depth': '1', 'User-Agent': 'vdirsyncer', 'Content-Type': 'application/xml; charset=UTF-8'}
    debug: 
    debug:     <d:propfind xmlns:d="DAV:">
    debug:         <d:prop>
    debug:             <d:resourcetype />
    debug:         </d:prop>
    debug:     </d:propfind>
    debug:     
    debug: Sending request...
    debug: 207
    debug: {'Content-Length': '818', 'Content-Type': 'text/xml; charset="utf-8"'}
    debug: <ns0:multistatus xmlns:ns0="DAV:"><ns0:response><ns0:href>/user/calendars/</ns0:href><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:propstat><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:prop><ns0:resourcetype><ns0:collection /></ns0:resourcetype></ns0:prop></ns0:propstat></ns0:response><ns0:response><ns0:href>/gueux/calendars/home/</ns0:href><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:propstat><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:prop><ns0:resourcetype><ns0:collection /></ns0:resourcetype></ns0:prop></ns0:propstat></ns0:response><ns0:response><ns0:href>/gueux/calendars/work/</ns0:href><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:propstat><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:prop><ns0:resourcetype><ns0:collection /></ns0:resourcetype></ns0:prop></ns0:propstat></ns0:response></ns0:multistatus>
    debug: Skipping, not of resource type {urn:ietf:params:xml:ns:caldav}calendar: <Element '{DAV:}response' at 0x7fc2353cbe58>
    debug: Skipping, not of resource type {urn:ietf:params:xml:ns:caldav}calendar: <Element '{DAV:}response' at 0x7fc235362048>
    debug: Skipping, not of resource type {urn:ietf:params:xml:ns:caldav}calendar: <Element '{DAV:}response' at 0x7fc235362408>
    calendars_remote:
    warning: No collection "home" found for storage calendars_remote.
    Should vdirsyncer attempt to create it? [y/N]: y
    debug: PROPFIND http://localhost:8080/
    debug: {'Depth': '1', 'User-Agent': 'vdirsyncer', 'Content-Type': 'application/xml; charset=UTF-8'}
    debug: 
    debug:     <d:propfind xmlns:d="DAV:">
    debug:         <d:prop>
    debug:             <d:resourcetype />
    debug:         </d:prop>
    debug:     </d:propfind>
    debug:     
    debug: Sending request...
    debug: 207
    debug: {'Content-Length': '253', 'Content-Type': 'text/xml; charset="utf-8"'}
    debug: <ns0:multistatus xmlns:ns0="DAV:"><ns0:response><ns0:href>/</ns0:href><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:propstat><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:prop><ns0:resourcetype /></ns0:prop></ns0:propstat></ns0:response></ns0:multistatus>
    debug: Skipping, not of resource type {urn:ietf:params:xml:ns:caldav}calendar: <Element '{DAV:}response' at 0x7fc2353cbe58>
    debug: Given URL is not a homeset URL
    debug: PROPFIND http://localhost:8080/
    debug: {'Depth': '0', 'User-Agent': 'vdirsyncer', 'Content-Type': 'application/xml; charset=UTF-8'}
    debug: 
    debug:         <d:propfind xmlns:d="DAV:">
    debug:             <d:prop>
    debug:                 <d:current-user-principal />
    debug:             </d:prop>
    debug:         </d:propfind>
    debug:         
    debug: Sending request...
    debug: 207
    debug: {'Content-Length': '318', 'Content-Type': 'text/xml; charset="utf-8"'}
    debug: <ns0:multistatus xmlns:ns0="DAV:"><ns0:response><ns0:href>/</ns0:href><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:propstat><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:prop><ns0:current-user-principal><ns0:href>/user/</ns0:href></ns0:current-user-principal></ns0:prop></ns0:propstat></ns0:response></ns0:multistatus>
    debug: PROPFIND http://localhost:8080/user/
    debug: {'Depth': '0', 'User-Agent': 'vdirsyncer', 'Content-Type': 'application/xml; charset=UTF-8'}
    debug: 
    debug:     <d:propfind xmlns:d="DAV:" xmlns:c="urn:ietf:params:xml:ns:caldav">
    debug:         <d:prop>
    debug:             <c:calendar-home-set />
    debug:         </d:prop>
    debug:     </d:propfind>
    debug:     
    debug: Sending request...
    debug: 207
    debug: {'Content-Length': '366', 'Content-Type': 'text/xml; charset="utf-8"'}
    debug: <ns0:multistatus xmlns:ns0="DAV:" xmlns:ns1="urn:ietf:params:xml:ns:caldav"><ns0:response><ns0:href>/user/</ns0:href><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:propstat><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:prop><ns1:calendar-home-set><ns0:href>/gueux/calendars/</ns0:href></ns1:calendar-home-set></ns0:prop></ns0:propstat></ns0:response></ns0:multistatus>
    debug: PROPFIND http://localhost:8080/user/calendars/
    debug: {'Depth': '1', 'User-Agent': 'vdirsyncer', 'Content-Type': 'application/xml; charset=UTF-8'}
    debug: 
    debug:     <d:propfind xmlns:d="DAV:">
    debug:         <d:prop>
    debug:             <d:resourcetype />
    debug:         </d:prop>
    debug:     </d:propfind>
    debug:     
    debug: Sending request...
    debug: 207
    debug: {'Content-Length': '818', 'Content-Type': 'text/xml; charset="utf-8"'}
    debug: <ns0:multistatus xmlns:ns0="DAV:"><ns0:response><ns0:href>/user/calendars/</ns0:href><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:propstat><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:prop><ns0:resourcetype><ns0:collection /></ns0:resourcetype></ns0:prop></ns0:propstat></ns0:response><ns0:response><ns0:href>/gueux/calendars/home/</ns0:href><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:propstat><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:prop><ns0:resourcetype><ns0:collection /></ns0:resourcetype></ns0:prop></ns0:propstat></ns0:response><ns0:response><ns0:href>/gueux/calendars/work/</ns0:href><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:propstat><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:prop><ns0:resourcetype><ns0:collection /></ns0:resourcetype></ns0:prop></ns0:propstat></ns0:response></ns0:multistatus>
    debug: Skipping, not of resource type {urn:ietf:params:xml:ns:caldav}calendar: <Element '{DAV:}response' at 0x7fc2353cbf98>
    debug: Skipping, not of resource type {urn:ietf:params:xml:ns:caldav}calendar: <Element '{DAV:}response' at 0x7fc235362598>
    debug: Skipping, not of resource type {urn:ietf:params:xml:ns:caldav}calendar: <Element '{DAV:}response' at 0x7fc235362368>
    debug: PROPFIND http://localhost:8080/
    debug: {'Depth': '0', 'User-Agent': 'vdirsyncer', 'Content-Type': 'application/xml; charset=UTF-8'}
    debug: 
    debug:         <d:propfind xmlns:d="DAV:">
    debug:             <d:prop>
    debug:                 <d:current-user-principal />
    debug:             </d:prop>
    debug:         </d:propfind>
    debug:         
    debug: Sending request...
    debug: 207
    debug: {'Content-Length': '318', 'Content-Type': 'text/xml; charset="utf-8"'}
    debug: <ns0:multistatus xmlns:ns0="DAV:"><ns0:response><ns0:href>/</ns0:href><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:propstat><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:prop><ns0:current-user-principal><ns0:href>/user/</ns0:href></ns0:current-user-principal></ns0:prop></ns0:propstat></ns0:response></ns0:multistatus>
    debug: PROPFIND http://localhost:8080/user/
    debug: {'Depth': '0', 'User-Agent': 'vdirsyncer', 'Content-Type': 'application/xml; charset=UTF-8'}
    debug: 
    debug:     <d:propfind xmlns:d="DAV:" xmlns:c="urn:ietf:params:xml:ns:caldav">
    debug:         <d:prop>
    debug:             <c:calendar-home-set />
    debug:         </d:prop>
    debug:     </d:propfind>
    debug:     
    debug: Sending request...
    debug: 207
    debug: {'Content-Length': '366', 'Content-Type': 'text/xml; charset="utf-8"'}
    debug: <ns0:multistatus xmlns:ns0="DAV:" xmlns:ns1="urn:ietf:params:xml:ns:caldav"><ns0:response><ns0:href>/user/</ns0:href><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:propstat><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:prop><ns1:calendar-home-set><ns0:href>/gueux/calendars/</ns0:href></ns1:calendar-home-set></ns0:prop></ns0:propstat></ns0:response></ns0:multistatus>
    debug: MKCOL http://localhost:8080/user/calendars/home
    debug: {'User-Agent': 'vdirsyncer', 'Content-Type': 'application/xml; charset=UTF-8'}
    debug: <?xml version="1.0" encoding="utf-8" ?>
    debug:             <D:mkcol xmlns:D="DAV:">
    debug:                 <D:set>
    debug:                     <D:prop>
    debug:                         <D:resourcetype>
    debug:                             <D:collection/>
    debug:                             <ns0:calendar xmlns:ns0="urn:ietf:params:xml:ns:caldav" />
    debug:                         </D:resourcetype>
    debug:                     </D:prop>
    debug:                 </D:set>
    debug:             </D:mkcol>
    debug:         
    debug: Sending request...
    debug: 405
    debug: {}
    
    error: 405 Client Error: Method Not Allowed for url: http://localhost:8080/user/calendars/home
    critical: Unable to find or create collection "home" for storage "calendars_remote". Please create the collection yourself.
    error: 1 out of 1 tasks failed.

**Comment by legrostdg** [comment]
mmh, OK, it works, but only if the calendars are not empty (so, one has to run `vdirsyncer sync` before running `vdirsyncer discover` again).

**Comment by legrostdg** [comment]
Great, it also fixed an issue with davdroid! The calendars are also shown there now! For the first time ever, I'm able to have the same agenda on my phone and on my laptop :-). Thanks a lot!

**Comment by legrostdg** [comment]
Oh, another problem: I can't `vdirsyncer sync` my contacts anymore...

my vdirsyncer config:

    [pair my_contacts]
    a = "my_contacts_local"
    b = "my_contacts_remote"
    collections = null
    
    [storage my_contacts_local]
    type = "filesystem"
    path = "~/lib/contacts/"
    fileext = ".vcf"
    
    [storage my_contacts_remote]
    type = "carddav"
    url = "http://localhost:8080/user/contacts/"
    username = "user"
    password = "password"

`vdirsyncer discover`:

    $ vdirsyncer -vdebug discover my_contacts
    debug: Using 1 maximal workers.
    Discovering collections for pair my_contacts
    my_contacts_local:
    debug: PROPFIND http://localhost:8080/user/contacts/
    debug: {'Content-Type': 'application/xml; charset=UTF-8', 'User-Agent': 'vdirsyncer', 'Depth': '1'}
    debug: 
    debug:     <d:propfind xmlns:d="DAV:">
    debug:         <d:prop>
    debug:             <d:resourcetype />
    debug:         </d:prop>
    debug:     </d:propfind>
    debug:     
    debug: Sending request...
    debug: 404
    debug: {'Content-Type': 'text/plain; encoding="utf-8"', 'Content-Length': '0'}
    
    debug: Given URL is not a homeset URL
    debug: PROPFIND http://localhost:8080/user/contacts/
    debug: {'Content-Type': 'application/xml; charset=UTF-8', 'User-Agent': 'vdirsyncer', 'Depth': '0'}
    debug: 
    debug:         <d:propfind xmlns:d="DAV:">
    debug:             <d:prop>
    debug:                 <d:current-user-principal />
    debug:             </d:prop>
    debug:         </d:propfind>
    debug:         
    debug: Sending request...
    debug: 404
    debug: {'Content-Type': 'text/plain; encoding="utf-8"', 'Content-Length': '0'}
    
    debug: Trying out well-known URI
    debug: PROPFIND http://localhost:8080/.well-known/carddav
    debug: {'Content-Type': 'application/xml; charset=UTF-8', 'User-Agent': 'vdirsyncer', 'Depth': '0'}
    debug: 
    debug:         <d:propfind xmlns:d="DAV:">
    debug:             <d:prop>
    debug:                 <d:current-user-principal />
    debug:             </d:prop>
    debug:         </d:propfind>
    debug:         
    debug: Sending request...
    debug: 404
    debug: {'Content-Type': 'text/plain; encoding="utf-8"', 'Content-Length': '0'}
    
    debug:   File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.15.1.dev24+ng8a1e7a8-py3.5.egg/vdirsyncer/cli/discover.py", line 204, in _print_collections
    debug:     discovered = get_discovered()
    debug:   File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.15.1.dev24+ng8a1e7a8-py3.5.egg/vdirsyncer/cli/discover.py", line 133, in get_self
    debug:     return self._discovered
    debug:   File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.15.1.dev24+ng8a1e7a8-py3.5.egg/vdirsyncer/utils.py", line 170, in __get__
    debug:     obj.__dict__[self.__name__] = result = self.fget(obj)
    debug:   File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.15.1.dev24+ng8a1e7a8-py3.5.egg/vdirsyncer/cli/discover.py", line 142, in _discovered
    debug:     return handle_storage_init_error(self._cls, self._config)
    debug:   File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.15.1.dev24+ng8a1e7a8-py3.5.egg/vdirsyncer/cli/discover.py", line 138, in _discovered
    debug:     discovered = list(self._cls.discover(**self._config))
    debug:   File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.15.1.dev24+ng8a1e7a8-py3.5.egg/vdirsyncer/storage/dav.py", line 235, in discover
    debug:     for c in self.find_collections():
    debug:   File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.15.1.dev24+ng8a1e7a8-py3.5.egg/vdirsyncer/storage/dav.py", line 195, in find_collections
    debug:     return self._find_collections_impl(self.find_home())
    debug:   File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.15.1.dev24+ng8a1e7a8-py3.5.egg/vdirsyncer/storage/dav.py", line 171, in find_home
    debug:     url = self.find_principal()
    debug:   File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.15.1.dev24+ng8a1e7a8-py3.5.egg/vdirsyncer/storage/dav.py", line 142, in find_principal
    debug:     return self._find_principal_impl(self._well_known_uri)
    debug:   File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.15.1.dev24+ng8a1e7a8-py3.5.egg/vdirsyncer/storage/dav.py", line 156, in _find_principal_impl
    debug:     data=body)
    debug:   File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.15.1.dev24+ng8a1e7a8-py3.5.egg/vdirsyncer/storage/dav.py", line 358, in request
    debug:     return http.request(method, url, session=self._session, **more)
    debug:   File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.15.1.dev24+ng8a1e7a8-py3.5.egg/vdirsyncer/http.py", line 181, in request
    debug:     raise exceptions.NotFoundError(r.reason)
    warning: Failed to discover collections for my_contacts_remote, use `-vdebug` to see the full traceback.
    Saved for my_contacts: collections = null

`vdirsyncer sync`:

    $ vdirsyncer -vdebug sync my_contacts
    debug: Using 1 maximal workers.
    Syncing my_contacts
    debug: Loaded status for my_contacts
    debug: PROPFIND http://localhost:8080/user/contacts/
    debug: {'Depth': '1', 'User-Agent': 'vdirsyncer', 'Content-Type': 'application/xml; charset=UTF-8'}
    debug: <?xml version="1.0" encoding="utf-8" ?>
    debug:             <D:propfind xmlns:D="DAV:">
    debug:                 <D:prop>
    debug:                     <D:resourcetype/>
    debug:                     <D:getcontenttype/>
    debug:                     <D:getetag/>
    debug:                 </D:prop>
    debug:             </D:propfind>
    debug:             
    debug: Sending request...
    debug: 404
    debug: {'Content-Length': '0', 'Content-Type': 'text/plain; encoding="utf-8"'}
    
    error: Unknown error occured for my_contacts: Not Found
    error: Use `-vdebug` to see the full traceback.
    debug:   File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.15.1.dev24+ng8a1e7a8-py3.5.egg/vdirsyncer/cli/tasks.py", line 73, in sync_collection
    debug:     partial_sync=pair.partial_sync
    debug:   File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.15.1.dev24+ng8a1e7a8-py3.5.egg/vdirsyncer/sync.py", line 255, in sync
    debug:     b_info.prepare_new_status()
    debug:   File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.15.1.dev24+ng8a1e7a8-py3.5.egg/vdirsyncer/sync.py", line 150, in prepare_new_status
    debug:     for href, etag in self.storage.list():
    debug:   File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.15.1.dev24+ng8a1e7a8-py3.5.egg/vdirsyncer/storage/dav.py", line 609, in list
    debug:     headers=headers)
    debug:   File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.15.1.dev24+ng8a1e7a8-py3.5.egg/vdirsyncer/storage/dav.py", line 358, in request
    debug:     return http.request(method, url, session=self._session, **more)
    debug:   File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.15.1.dev24+ng8a1e7a8-py3.5.egg/vdirsyncer/http.py", line 181, in request
    debug:     raise exceptions.NotFoundError(r.reason)
    error: 1 out of 2 tasks failed.

**Comment by jelmer** [comment]
calendars/addressbooks that are empty not appearing is caused by https://github.com/jelmer/xandikos/issues/16

**Comment by legrostdg** [comment]
OK, I had deleted the `contacts` directory on the server, to test this, and forgot to recreate it.
