### ISSUE TITLE
Problem with macOS CardDav

### ISSUE THREAD

**Issue by 1995parham** [jelmer/xandikos#277]
I have a server on `192.168.73.2:8432`, and it works greatly with Android and iPhone. On macOS I have no problem with CalDav but CardDav is not working. I've attached my configuration.

<img width="712" alt="Screenshot 2023-12-03 at 6 15 57 PM" src="https://github.com/jelmer/xandikos/assets/8181240/fbdc9724-a43a-48a9-8d15-994f72f9486f">

**Comment by jelmer** [comment]
Sorry, only noticed this just now - @1995parham, did you manage to resolve it somehow?

**Comment by 1995parham** [comment]
I do research about it and provide answer here for future reference. Seems the issue is related to the macOS version, in which you cannot use ip domains.
