### ISSUE TITLE
Xandikos integration in Mail-in-a-Box

### ISSUE THREAD

**Issue by cmonty14** [jelmer/xandikos#278]
Hi,
I'm a fan of simple and thin software solutions.
Searching a thin solution for Cal/CardDav and I think _Xandikos_ is a perfect match. _[Radicale](https://radicale.org/v3.html)_ would also match, however it's not actively maintained.
Searching a simple solution for mail server hosting [Mail-in-a-Box](https://mailinabox.email/) is a perfect match.

Now I wonder if these two perfect solutions could be combined?

There's a [discussion](https://github.com/mail-in-a-box/mailinabox/issues/2164) in Mail-in-a-Box about this topic, but nobody has started integration of _Xandikos_, yet.

I'm not a developer and can hardly support this integration.
But as an end-user I would be happy to test it.

Ideally developers of _Xandikos_ and _Mail-in-a-Box_ would start collaboration on this topic in order to replace Mail-in-a-Box's currently used Cal/CardDav service Nextcloud.

THX

**Comment by jelmer** [comment]
If there are specific changes for Xandikos that would make it easier to integrate in Mail-in-a-box (issues or pull requests), then I'm happy to consider those. That said, I think most of the work here would be in Mail-in-a-box rather than Xandikos.
