### ISSUE TITLE
mimetypes.guess_type guesses the wrong vcard mimetype

### ISSUE THREAD

**Issue by untitaker** [jelmer/xandikos#30]
>>> mimetypes.guess_type('foo.vcf')
    ('text/x-vcard', None)

This breaks multiget for `address-data` for instance. I would recommend having a hardcoded translation table for the two mimetypes you actually need to support, instead of using `mimetypes`.

**Comment by jelmer** [comment]
Or, alternatively - read in the original set of mime types using mimetypes.read_mime_types(), then override the entries for ics/vcf files with known correct values?
