### ISSUE TITLE
Add a SSL Certificates to xandikos.org

### ISSUE THREAD

**Issue by mommyune** [jelmer/xandikos#311]
Your website [xandikos.org](https://www.xandikos.org/) does not own a valid SSL certificate

You can request one for free with [certbot](https://certbot.eff.org/)

![image](https://github.com/jelmer/xandikos/assets/99808967/5e124f3e-b4b2-4585-95d9-6100137cb3cc)

**Comment by jelmer** [comment]
Related to #312 - closing this in favour of that bug.
