### ISSUE TITLE
The docker container seems to ignore the "DEFAULTS" environment variable and always creates default directories

### ISSUE THREAD

**Issue by Void-0000** [jelmer/xandikos#342]
Not sure if I'm just doing it wrong, but I've tried setting "DEFAULT=no" from both docker-compose and docker run but no matter what I do it always creates the default calendar when it starts.

**Comment by jelmer** [comment]
That bit of the docs is outdated I think. I've pushed a fix - you probably want to set AUTOCREATE to something other than "defaults"
