### ISSUE TITLE
support WebDAV Mount (RFC4709)

### ISSUE THREAD

**Issue by jelmer** [jelmer/xandikos#48]
See http://www.rfc-base.org/rfc-4709.html

**Comment by jelmer** [comment]
Is there actually any use in implementing this? As far as I can tell, there is only one implementation of it - also server side. This is in SabreDAV: http://sabre.io/dav/davmount/

**Comment by jelmer** [comment]
The only client that implements this is the proprietary Xythos Drive (mentioned in the RFC); https://www.xythosondemand.com/xod/support/xythos_drive.html

**Comment by jelmer** [comment]
I have an implementation of this, but no way to test it. For the moment, I'm going to hold off on merging this until somebody can convince me why this is a good idea.

**Comment by minfrin** [comment]
You need to be convinced that following an RFC is a good idea...?

**Comment by jelmer** [comment]
s/following/implementing/

Implementing this RFC is not a requirement for any of the RFCs that Xandikos actually cares about. I also don't see any clients that actually support it.

**Comment by minfrin** [comment]
Built it, and they will come.

**Comment by jelmer** [comment]
Sure, I'd do that, if I thought this RFC was a good idea and needed wider adoption. I'm not convinced, and the fact that there are no other implementations doesn't help.

I'm open to changing my mind, but until I do there's other functionality I'd rather focus on.

**Comment by raphidae** [comment]
Just came across while researching this and would like to note that CommuniGate Pro implements this.

See: https://www.communigate.ru/communigatepro/HTTP.html

**Comment by jelmer** [comment]
@raphidae do you have a reference for it implementing this RFC? Is it a server or a client?
