### ISSUE TITLE
git hooks of collection repositories are executed with cwd = XANDIKOSPATH

### ISSUE THREAD

**Issue by Fabian-Gruenbichler** [jelmer/xandikos#65]
might be related to https://github.com/jelmer/dulwich/issues/386 (which was never cleared up ;)).

if you configure a git hook in a collection repository (i.e., to automatically push any local commits to a remote via post-commit), they are not executed from within that repository, but from XANDIKOSPATH. this means that any calls to "git" in such a hook either fail because they don't find a repository, or, if running from git HEAD, attempt to do whatever they are supposed to do to the wrong repository.

while this can be worked around in the hook, it is a bit cumbersome, and IMHO it would be nicer to integrate this into either xandikos or dulwich. if this is something you'd like to see, I can whip up a PR :)

**Comment by jelmer** [comment]
This was fixed in dulwich. Thanks!
