### ISSUE TITLE
SCRIPT_NAME missing from documentation

### ISSUE THREAD

**Issue by ecksun** [jelmer/xandikos#67]
My testing suggests that SCRIPT_NAME needs to be defined when running via uwsgi/nginx.

Without it I get the following exception:

```
Traceback (most recent call last):
  File "./xandikos/webdav.py", line 1751, in __call__
    return do.handle(environ, start_response, self)
  File "./xandikos/webdav.py", line 273, in wrapper
    responses = req_fn(self, environ, *args, **kwargs)
  File "./xandikos/webdav.py", line 1502, in handle
    app._get_resource_from_environ(environ))
  File "./xandikos/webdav.py", line 1711, in _get_resource_from_environ
    href = (environ['SCRIPT_NAME'] + path)
KeyError: 'SCRIPT_NAME'
```

I tried to figure out the purpose of `SCRIPT_NAME` by reading the code. For example `_get_resource_from_environ` (included below). Though I can not understand why `SCRIPT_NAME` should ever be the prefix of the URL, perhaps some refactoring could help improve readability.

```python3
    def _get_resource_from_environ(self, environ):
        path = path_from_environ(environ, 'PATH_INFO')
        href = (environ['SCRIPT_NAME'] + path)
        r = self.backend.get_resource(path)
        return (href, path, r)
```

Thus, some suggestions:

- Refactor usage of `SCRIPT_NAME` so its purpose becomes clear
- Document purpose of `SCRIPT_NAME`
- Assign a good default value to `SCRIPT_NAME`

**Comment by jelmer** [comment]
the convention is that SCRIPT_NAME is set to the path at which the script (i.e. xandikos) can be reached.

So if you're running xandikos at /xan and are accessing a calendar path at /calendar, then:

* $SCRIPT_NAME is set to /xan 
* $PATH_INFO is set to /calendar

**Comment by jelmer** [comment]
This is a nginx specific issue: https://uwsgi-docs.readthedocs.io/en/latest/Nginx.html#hosting-multiple-apps-in-the-same-process-aka-managing-script-name-and-path-info
