### ISSUE TITLE
Traceback with 0.0.6

### ISSUE THREAD

**Issue by matthiasbeyer** [jelmer/xandikos#70]
```
Traceback (most recent call last):
  File "/nix/store/p37npidsgzbyqaryjz40brgkrcdvqczh-xandikos-0.0.6/bin/.xandikos-wrapped", line 30, in <module>
    from xandikos.web import main
  File "/nix/store/p37npidsgzbyqaryjz40brgkrcdvqczh-xandikos-0.0.6/lib/python2.7/site-packages/xandikos/web.py", line 37, in <module>
    from xandikos import (access, apache, caldav, carddav, quota, sync, webdav,
  File "/nix/store/p37npidsgzbyqaryjz40brgkrcdvqczh-xandikos-0.0.6/lib/python2.7/site-packages/xandikos/access.py", line 25, in <module>
    from xandikos import webdav
  File "/nix/store/p37npidsgzbyqaryjz40brgkrcdvqczh-xandikos-0.0.6/lib/python2.7/site-packages/xandikos/webdav.py", line 33, in <module>
    import urllib.parse
ImportError: No module named parse
```

I'm in the process of packaging xandikos for nixos (because I'm still using f**king owncloud to sync my contacts and calendars from two computers and a android device), but am running into this error.

Can you tell what's wrong?

The dependencies I pass into the package are: 

* icalendar
* dulwich
* defusedxml
* jinja2

which should be all dependencies, right?

**Comment by jelmer** [comment]
On Wed, Nov 01, 2017 at 04:16:04PM +0000, Matthias Beyer wrote:
> ```
> Traceback (most recent call last):
>   File "/nix/store/p37npidsgzbyqaryjz40brgkrcdvqczh-xandikos-0.0.6/bin/.xandikos-wrapped", line 30, in <module>
>     from xandikos.web import main
What is .xandikos-wrapped?

>   File "/nix/store/p37npidsgzbyqaryjz40brgkrcdvqczh-xandikos-0.0.6/lib/python2.7/site-packages/xandikos/web.py", line 37, in <module>
>     from xandikos import (access, apache, caldav, carddav, quota, sync, webdav,
>   File "/nix/store/p37npidsgzbyqaryjz40brgkrcdvqczh-xandikos-0.0.6/lib/python2.7/site-packages/xandikos/access.py", line 25, in <module>
>     from xandikos import webdav
>   File "/nix/store/p37npidsgzbyqaryjz40brgkrcdvqczh-xandikos-0.0.6/lib/python2.7/site-packages/xandikos/webdav.py", line 33, in <module>
>     import urllib.parse
> ImportError: No module named parse
> ```
> 
> I'm in the process of packaging xandikos for nixos (because I'm still using f**king owncloud to sync my contacts and calendars from two computers and a android device), but am running into this error.
> 
> Can you tell what's wrong?
> 
> The dependencies I pass into the package are: 
> 
> * icalendar
> * dulwich
> * defusedxml
> * jinja2
> 
> which should be all dependencies, right?
You appear to be running Xandikos in Python2.7; it is Python3 only.

Jelmer

**Comment by matthiasbeyer** [comment]
Hi, thanks for getting back on this so fast.

`.xandikos-wrapped` is a nixos wrapper, because we do not have `/usr/bin` and these things, we have to adjust shebangs (which is done automatically). You don't need to worry about this bit!

> Python3

okay, going to fixup my package definition...

**Comment by matthiasbeyer** [comment]
I'm running into an issue with `fastimport` which is a dependency of `dulwich` - `fastimport` is not python3 in nixpkgs because it fails with a syntax error in the tests when using the python3 interpreter,...

Which version of dulwich do you use for xandikos? Maybe I can downgrate dulwich?

**Comment by jelmer** [comment]
On Wed, Nov 01, 2017 at 04:32:35PM +0000, Matthias Beyer wrote:
> I'm running into an issue with `fastimport` which is a dependency of `dulwich` - `fastimport` is not python3 in nixpkgs because it fails with a syntax error in the tests when using the python3 interpreter,...
> 
> Which version of dulwich do you use for xandikos? Maybe I can downgrate dulwich?
fastimport is an optional dependency of dulwich; dulwich and xandikos should
work fine without it.

Separately, I'd be interested in the syntax error you're seeing with fastimport on Python3. The testsuite passes for me with Python3, as well as on travis:

https://travis-ci.org/jelmer/python-fastimport/builds/181744746

Jelmer

**Comment by matthiasbeyer** [comment]
```

======================================================================
ERROR: fastimport.tests.test_parser (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: fastimport.tests.test_parser
Traceback (most recent call last):
  File "/nix/store/2lb6nn8ivk1alhckv43n7734lqwbw7h9-python3-3.6.2/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/nix/store/2lb6nn8ivk1alhckv43n7734lqwbw7h9-python3-3.6.2/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/tmp/nix-build-python3.6-fastimport-0.9.4.drv-0/fastimport-0.9.4/fastimport/tests/test_parser.py", line 202
    self.assertEqual(0100644, file_cmd1.mode)
                           ^
SyntaxError: invalid token
```

**Comment by jelmer** [comment]
On Wed, Nov 01, 2017 at 04:36:47PM +0000, Matthias Beyer wrote:
> ```
> 
> ======================================================================
> ERROR: fastimport.tests.test_parser (unittest.loader._FailedTest)
> ----------------------------------------------------------------------
> ImportError: Failed to import test module: fastimport.tests.test_parser
> Traceback (most recent call last):
>   File "/nix/store/2lb6nn8ivk1alhckv43n7734lqwbw7h9-python3-3.6.2/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
>     module = self._get_module_from_name(name)
>   File "/nix/store/2lb6nn8ivk1alhckv43n7734lqwbw7h9-python3-3.6.2/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
>     __import__(name)
>   File "/tmp/nix-build-python3.6-fastimport-0.9.4.drv-0/fastimport-0.9.4/fastimport/tests/test_parser.py", line 202
>     self.assertEqual(0100644, file_cmd1.mode)
>                            ^
> SyntaxError: invalid token
> ```
There are two more upstream releases that add Python 3 support; latest is 0.9.6.

Jelmer

**Comment by matthiasbeyer** [comment]
Solved. Thanks for your support!

**Comment by jelmer** [comment]
On Wed, Nov 01, 2017 at 04:46:38PM +0000, Matthias Beyer wrote:
> Solved. Thanks for your support!
You're welcome. Please do file issues if you run into problems. I'm in particular interested in hearing about what can be done to improve the setup procedure.
