### ISSUE TITLE
Is there any way other than storing cleartext password in configuration?

### ISSUE THREAD

**Issue by adamcavendish** [jelmer/xandikos#72]
It might be very unsafe to just specify the password in the configuration.

**Comment by polyzen** [comment]
Serve with [nginx](https://nginx.org/en/docs/http/ngx_http_auth_basic_module.html) or the like.

**Comment by jelmer** [comment]
As polyzen says, I'd suggest running a reverse HTTP proxy that can do the authentication. 

See "Production" in the README for details.
