### ISSUE TITLE
Add "CardBook" to Tested Clients

### ISSUE THREAD

**Issue by ovari** [jelmer/xandikos#77]
The [CardBook](https://gitlab.com/CardBook/CardBook) add-on for Thunderbird is available from [ATN](https://addons.thunderbird.net/addon/cardbook/).

Please add [CardBook](https://gitlab.com/CardBook/CardBook) to your list of [Tested Clients](https://www.xandikos.org/clients.html).

Thank you

**Comment by jelmer** [comment]
Have you actually tested CardBook with Xandikos? Last I checked CardBook had issues with line endings.

**Comment by ovari** [comment]
What was the last version of CardBook which you used that didn't work?

An issue has been created at:
https://gitlab.com/CardBook/CardBook/issues/315

If you can provide more details to enable the developer to fix it would be appreciated.

Thank you

**Comment by jelmer** [comment]
Are you actually using CardBook with Xandikos without issues, and it doesn't trigger a full rewrite that strips \rs whenever a single field changes?
