### ISSUE TITLE
Serving xandikos from subdirectory

### ISSUE THREAD

**Issue by tusj** [jelmer/xandikos#79]
I want to setup xandikos to listen to requests on localhost/dav. Here's the relevant excerpts of the nginx and uwsgi configurations I use:
```
location /dav {
    include uwsgi_params;  
    uwsgi_pass unix://tmp/uwsgi_xandikos.sock;  
}
```
uwsgi:
```
[uwsgi]
socket = /tmp/uwsgi_xandikos.sock;
manage-script-name = true
mount = /dav=xandikos.wsgi:app
```

This works except that the links generated by xandikos do not take in account the mount root at /dav,  so xandikos still generates the links as if it would be served from /.

There's a switch --route-prefix available for xandikos from the commandline that is supposed to be used for this purpose, but when serving xandikos (from the commandline, without uwsgi) with --route-prefix=/dav/, I see no change in behavior.

I am relatively inexperienced with both nginx, uwsgi and xandikos so I might be missing something simple.

**Comment by tusj** [comment]
If I run xandikos like this:
`xandikos --defaults --current-user-principal /dav/tusj --listen-address 0.0.0.0 -p 8010 -d /external/xandikos/tusj` I get the correct listing on localhost:8010/dav/tusj. The main listing still resides on localhost:8010/ and not localhost:8010/dav. Using --route-prefix still seems to change nothing.

**Comment by tusj** [comment]
I see that using `env = CURRENT_USER_PRINCIPAL=/dav/tusj/` resolves my issue. I do find it unintuitive that it the variable is called CURRENT_USER_PRINCIPAL when actually it sets that path as well.

**Comment by jelmer** [comment]
I agree the CURRENT_USER_PRINCIPAL variable is a bit confusing when used in conjunction with --route_prefix; this will probably change when multi-user support is added.
