### ISSUE TITLE
[Question]: Is it possible to import calendar/addressbook

### ISSUE THREAD

**Issue by mbauhardt** [jelmer/xandikos#83]
Hi,
i have a question if it is possible to import a calendar or addressbook from another system.
my use case is i want to switch from radicale to xandikos. but i have several calendar events and addressbook entries.
do you think to copy all *.ics or *.vcf files into a collection owned by xandikos and then the events and contacts are available. using git commit to commit the files into the repo.
or do you see another way?

**Comment by legrostdg** [comment]
You can use `vdirsyncer` for this.

**Comment by jelmer** [comment]
Yeah, you can just commit the vcf and ics files to the repository directly. There is nothing special about the repository, it's just like any other git repository.

If you have both the radicale and the xandikos server running at the same time, then you can also use a WebDAV/caldav/carddav client to copy over the items. E.g. vdirsyncer, as legrostdg suggests.

**Comment by mbauhardt** [comment]
hey,
thx @legrostdg @jelmer 

clever/logic idea to use vdirsyncer to sync the contact from a to b.
will do it.
