### ISSUE TITLE
ios clients do not notice deleted events or deleted addressbook entries

### ISSUE THREAD

**Issue by Peter4825** [jelmer/xandikos#92]
How to reproduce:
1) set up 2 clients to use the same xandikos server, at least one client must be ios (iphone, ipad), 
2) create an appointment in the calendar
3) refresh the ios caldav client to make sure it has seen the appointment, that the appointment is present in the calendar view
4) delete the appointment with the other client
5) refresh the ios caldav client to make sure it has re-read everything relevant on the server

Expected result: the ios client does no longer see the appointment
Actual result: the ios client still sees the appointment

As far as I know:
- the same behaviour is true for carddav
- tested versions ios 9 trough 12, they all have the same issue

**Comment by jelmer** [comment]
This should be fixed by #92
